language: java
jdk: oraclejdk8
dist: trusty

# Skip "install" stage:
install: true

# Use container-based infrastructure:
sudo: false

addons:
  apt:
    packages:
    - metacity

env:
  - PLATFORM=e3.8
    JDK=1.7
  - PLATFORM=e4.6
    JDK=1.8
  - PLATFORM=e4.7
    JDK=1.8
  - PLATFORM=e4.8
    JDK=1.8
  - PLATFORM=e4.9
    JDK=1.8
  - PLATFORM=e4.10
    JDK=1.8
  - PLATFORM=e4.11
    JDK=1.8
  - PLATFORM=e4.12
    JDK=1.8

script: bash .travis.sh
